[project]
name = "adv-2025"
version = "0.1.0"
description = "solutions of Advent of Code 2025"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy==2.3.5"
]

[project.optional-dependencies]
dev = [
    "pytest==9.0.1",
    "pytest-xdist==3.8.0",
    "pylint==4.0.3",
    "flake8==7.3.0",
    "flake8-bugbear==25.10.21",
    "flake8-pytest-style==2.2.0",
    "ruff==0.14.6",
    "coverage==7.12.0",
    "black==25.11.0",
    "mypy==1.18.2"
]
